[install]
# Use exact versions for better reproducibility
exact = false

[install.scopes]
# Configure any scoped packages if needed

[test]
# Configure test environment
preload = ["./test/setup.ts"]

[run]
# Configure run environment
bun = true

# Node.js compatibility
node_modules = true 